### ISSUE TITLE
Внести правки в FS

### ISSUE THREAD

**Issue by vspochernin** [vspochernin/tesseract#3]
Необходимо внести правки в первую версию функциональной спецификации, в соответствии со следующими замечаниями:
- [x] Добавить ограничения на пароль (точно ограничить его длину как сверху, так и снизу, возможно, потребовать наличия цифр или спец символов).
- [x] Добавить ограничения на логин (также ограничить длину и возможность использования только обычных символов и цифр).
- [x] Возможно, на равне с обычной авторизацией, сделать авторизацию через Google OAuth API. ***Влад должен сказать, не сложно ли это сделать через телефон***.
- [x] Определить динамическую подгрузку активов (чтобы на экране одновременно отображались n активов и они могли динамически подгружаться).
- [x] Определить, как будем считать изменение стоимости.
- [x] Определить, какая будет полная информация об активе.
- [x] Определить, откуда будут браться данные, говорящие о доверии к активу (т.е. определить, как мы будем назначать активу рискованность). (Создать заметку)
- [x] Определить, каким образом будут рекомендоваться активы для диверсификации. (Создать заметку)
- [x] Исключить возможность пользователю выбирать количество активов для диверсификации.
- [x] Добавить возможность выхода из аккаунта.

**Comment by ithersta** [comment]
> * Возможно, на равне с обычной авторизацией, сделать авторизацию через Google OAuth API.

Там какая-то небольшая запара с получением ключа в Google Cloud, но со стороны андроида всё просто
